### ISSUE TITLE
 eyes[command_name]: Cannot read property 'assertionsDisabled' of undefined if invoking along with "run" command

### ISSUE THREAD

**Issue by learningandworking** [applitools/applitools-for-selenium-ide#3]
Setup:
- Latest Chrome version on Windows 10: Version 78.0.3904.108 

Scenario:
- TC1: Login Test: named "Login"
- TC2: Create Group and Task
![image](https://user-images.githubusercontent.com/26406558/69911541-75d3ad00-144f-11ea-8065-976fb28dca07.png)

Run TC2 in GUI mode and get issue
` eyesCheckWindow: Cannot read property 'assertionsDisabled' of undefined`

If I remove "run" command in TC2, this issue has gone.

Notes: Apply for all eyes[command_name]

**Comment by tourdedave** [comment]
This is actually a bug in Selenium IDE. I just committed a fix [here](https://github.com/SeleniumHQ/selenium-ide/commit/5bef44e252108bf1bcc38804114f0b2aa7fffb93). I'll get it out in the next release and update you when it's available.

**Comment by tourdedave** [comment]
The fix has been released in [`v3.16.1`](https://github.com/SeleniumHQ/selenium-ide/releases/tag/v3.16.1) of Selenium IDE. It's just been published to the Chrome and Firefox web stores and should be available later today.
